name: MachineBukkit
main: tk.gjz010.machinebukkit.MachineBukkit
softdepend: [SQLibrary]
version: 0.0.1
commands:
   gettestmachine:
      description: Test MachineBukkit.
      usage: /<command>
      permission: machinebukkit.admin
      permission-message: You don't have <permission>